MAX_LENGTH_RECIPE = 256
MAX_LENGTH_TAG = 32
MAX_LENGTH_TAG_SLUG = 32
MAX_LENGTH_INGREDIENT = 128
MAX_LENGTH_MEAS_UNIT = 64
MAX_LENGTH_SHORT_LINK = 128
MAX_LENGTH_LONG_LINK = 256
BOOL_CHOICES = ((0, 'False'), (1, 'True'))
